sonar.projectKey=cohort-9-mern-7434-anchalbai
sonar.projectName=cohort-9-mern-7434-anchalbai
sonar.host.url=http://localhost:9000
sonar.token=${env.SONAR_TOKEN}
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info


sonar.exclusions=**/coverage/**,**/node_modules/**,**/dist/**

sonar.coverage.exclusions=**/*.test.tsx,**/*.test.ts,**/vite.config.ts,**/setupTests.ts,**/*.config.js
